### ISSUE TITLE
部署一下呀，整个实例地址比较好

### ISSUE THREAD

**Issue by h7ml** [qiu-lzsnmb/glassmorphism-forum#1]

**Comment by Ocyss** [comment]
打算明天部署的，今晚lol去了😋












lzsnmb
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月12日(周二) 晚上10:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qiu-lzsnmb/glassmorphism-forum] 部署一下呀，整个实例地址比较好 (Issue #1)

**Comment by h7ml** [comment]
后端py flask吗，错误的账户密码处理貌似不是很友好。

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/178977868-5bbfea4f-4129-41b2-af61-067d7cac70a9.png)

**Comment by Ocyss** [comment]
现在在试一下。。刚刚是有这bug，因为有个python模块没安对。现在我这测试没问题的

**Comment by Ocyss** [comment]
不过你那登陆界面咋这样的啊
![1](https://user-images.githubusercontent.com/68412205/178978554-2f66e6c8-6f7e-4b6a-837e-f6160e77752e.png)

**Comment by h7ml** [comment]
你的登录表单没有做自适应

**Comment by h7ml** [comment]
![image](https://user-images.githubusercontent.com/55233292/178978984-fe9cc597-de8a-4077-b772-80a6eaaffe79.png)
 注册也存在问题

**Comment by Ocyss** [comment]
第一次打包，没发现有这么多问题，今晚好好学习一下。、。哎

**Comment by h7ml** [comment]
lol 咱不打了吗。。
